# Copiar a /etc/sssd/sssd.conf, luego:
#   sudo chmod 600 /etc/sssd/sssd.conf
#   sudo authselect select sssd --force
#   sudo systemctl enable --now sssd

[sssd]
services = nss, pam
domains = fis.epn.ec

[domain/fis.epn.ec]
id_provider = ldap
ldap_uri = ldaps://ldap1.fis.epn.ec, ldaps://ldap2.fis.epn.ec
ldap_search_base = dc=fis,dc=epn,dc=ec
ldap_tls_cacert = /etc/pki/ca-trust/source/anchors/fis-ca.crt
ldap_tls_reqcert = demand

auth_provider = krb5
krb5_server = kdc1.fis.epn.ec, kdc2.fis.epn.ec
krb5_backup_server = kdc2.fis.epn.ec
krb5_realm = FIS.EPN.EC

cache_credentials = true
enumerate = false
